variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  # - test
  - package
  - deploy

default:
  tags:
    - home

cache:
  paths:
    - .m2/repository
    - target

build-job:
  stage: build
  script:
    - echo "Maven Compile started"
    - "mvn clean compile"
  artifacts:
    paths:
      - target/*
      

package_job:
  stage:  package
  script:
    - echo "Maven package started"
    - "mvn clean install"

deploy_job:
  stage:  deploy
  script:
    - echo "Maven deploy started"
