variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

default:
  tags:
    - home-docker

cache:
  paths:
    - .m2/repository
    - target

build-job:
  stage: build
  script:
    - echo "Maven Compile started"
    - "mvn compile"

test-job:
  stage: test
  script:
    - echo "Maven test started"
    - "mvn test"


package_job:
  stage:  package
  script:
    - echo "Maven package started"
    - "mvn install"

deploy_job:
  stage:  deploy
  script:
    - echo "Maven deploy started"
