variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

build-job:
  image: maven:latest
  stage: build
  tags:
    - home
  script:
    - echo "Maven Compile started"
    - "mvn clean compile"
      
test-job:
  image: maven:latest
  stage: test
  tags:
    - home
  script:
    - echo "Maven test started"
    - "mvn clean test"
    
package_job:
  stage:  package
  image: maven:latest
  tags:
    - home
  script:
    - echo "Maven package started"
    - "mvn clean install"
  artifacts:
    paths:
      - target/*.jar

deploy_job:
  stage:  deploy
  image:  openjdk:8-jre-alpine
  tags:
    - home
  script:
    - echo "Maven deploy started"
    - "EXPOSE 8082"
    - "WORKIR /app"
    - COPY $CI_PROJECT_DIR/target/*.jar badgesystem.jar
    - CMD ["/usr/bin/java", "-jar", "/app/badgesystem.jar"]
