variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Maven Compile started"
    - "mvn compile"

# test-job:
#   stage: test
#   tags:
#     - docker
#   script:
#     - echo "Maven test started"
#     - "mvn test"


package_job:
  stage:  package
  tags:
    - docker
  script:
    - echo "Maven package started"
    - "mvn install"

deploy_job:
  stage:  deploy
  tags:
    - docker
  script:
    - echo "Maven deploy started"
