server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://192.168.200.153:3306/badgedb
    username: root
    password: example
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

keycloak:
  realm: restSecurity
  auth-server-url: http://localhost:8080/
  resource: restful-badge-system
  public-client: true
  bearer-only: true